### ISSUE TITLE
Support for Customizer

### ISSUE THREAD

**Issue by adampatterson** [adampatterson/Axe#37]
- [x] Background
- [x] #35 Header Graphics
- [x] #34 Enable or Disable a Sidebar
- [x] #44 Side bar on page, post, home
- [x] #42 Custom Fav Icon
- [x] #43 Custom Logo

Sidebars and Menus should be moved to the child theme, for demonstration, the built-up child theme.

**Comment by adampatterson** [comment]
Most customization will happen on each individual theme so that we don't end up with unnecessary code in our way.
